ffxi/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.contrib import admin
from django.contrib.auth import views as auth_views
from registration.backends.default.views import RegistrationView, ActivationView
from django_email_changer.views import CreateUserEmailModificationRequest, ActivateUserEmailModification, \
    ActivationEmailSentSuccessView

from ffxi.forms import RegistrationFormWithName

urlpatterns = [

    # AJAX
    url(r'^ajax/get-daily-stats/', 'ffxi.ajax.get_daily_stats', name='get_daily_stats'),
    url(r'^ajax/update-steps/', 'ffxi.ajax.update_steps', name='update_steps'),
    url(r'^ajax/add-exp-chain/', 'ffxi.ajax.add_exp_chain', name='add_exp_chain'),
    url(r'^ajax/get-signet-cost/', 'ffxi.ajax.get_signet_cost', name='get_signet_cost'),
    url(r'^ajax/get-level-cost/', 'ffxi.ajax.get_level_cost', name='get_level_cost'),
    url(r'^ajax/get-max-level/', 'ffxi.ajax.get_max_level', name='get_max_level'),

    # ffxi-gamify:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'ffxi.views.index', name='home'),
    url(r'^daily-tally/', 'ffxi.views.daily_tally', name='daily_tally'),
    url(r'^link-account/', 'ffxi.views.link_account', name='link_account'),
    url(r'^record-feats/', 'ffxi.views.record_feats', name='record_feats'),
    url(r'^ub3r1337-rank/', 'ffxi.views.ub3r1337_rank', name='ub3r1337_rank'),
    url(r'^character/(?P<charid>\d+)/(?P<charname>.+)/$', 'ffxi.views.character', name='character'),

    # django-email-changer
    url(r'accounts/email/change/activate/(?P<code>[^/]+)/',
        ActivateUserEmailModification.as_view(),
        name="django_change_email_activate_new_email"),
    url(r'^accounts/email/change/sent/$',
        ActivationEmailSentSuccessView.as_view(),
        name="django_change_email_sent_activation_email"),
    url(r'^accounts/email/change/$',
        CreateUserEmailModificationRequest.as_view(),
        name="django_email_changer_change_view"),

    # django-registration
    url(r'^accounts/$', RedirectView.as_view(url='/', )),
    # Fix for password reset
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^password/change/done/$',
        auth_views.password_change_done,
        name='password_change_done'),
    url(r'^accounts/password/reset/confirm/$',
        RedirectView.as_view(url='/', )),
    url(r'^accounts/password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': '/accounts/password/reset/done/'},
        name="password_reset"),
    url('^accounts/activate/$', ActivationView.as_view(),
        {'activation_key': 'None'},
        name='registration_activate'),
    # enable unique email registration feature
    url(r'^accounts/register/$',
        RegistrationView.as_view(form_class=RegistrationFormWithName),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

ffxi/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User

class DailyTally(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=date.today().strftime("%Y-%m-%d"))
    steps = models.PositiveIntegerField(default=0)
    
    # Cardio
    jumpjacks = models.PositiveSmallIntegerField(default=0)
    high_knees = models.PositiveSmallIntegerField(default=0)
    plank_jumps = models.PositiveSmallIntegerField(default=0)
    
    # Upper Body
    pushups = models.PositiveSmallIntegerField(default=0)

    # Lower Body
    squats = models.PositiveSmallIntegerField(default=0)

    # Abs
    climbers = models.PositiveSmallIntegerField(default=0)
    knee_pull_ins = models.PositiveSmallIntegerField(default=0)
    cross_crunches = models.PositiveSmallIntegerField(default=0)
    
    # Exp Chain Acheived
    chain = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'date')

class ExperienceHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=date.today().strftime("%Y-%m-%d"))
    exp = models.PositiveIntegerField(default=0)
    chain = models.DecimalField(max_digits=4, decimal_places=2)
    
class ExperienceStats(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exp = models.PositiveIntegerField(default=0)
    chain = models.DecimalField(default=1.0, max_digits=4, decimal_places=2)

class LinkedAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    acc_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=16)
    
class EnhancedSignetLevels(models.Model):
    exp = models.PositiveIntegerField()


ffxi/views.py
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User

from ffxi.forms import DailyTallyForm, LinkAccountForm, CharacterUpgradeForm, EnhancedSignetUpgrade
from ffxi.models import DailyTally, LinkedAccount

def index(request):
    return render_to_response('index.html', {}, RequestContext(request))
    
def daily_tally(request):
    if request.user.is_authenticated():
        if request.POST:
            form = DailyTallyForm(request.POST)
            if form.is_valid():
                dt = form.save(request.user, request.POST)
                if request.is_ajax():
                    return HttpResponse('saved')
                else:
                    return HttpResponseRedirect('/daily-tally/')
            else:
                if request.is_ajax():
                    return HttpResponse(form.errors)
        else:
            form = DailyTallyForm()
            return render_to_response('daily_tally.html', {'form': form}, RequestContext(request))
    else:
        return HttpResponseRedirect('/')

def link_account(request):
    if request.user.is_authenticated():
        if request.POST:
            form = LinkAccountForm(request.POST)
            if form.is_valid():
                status = form.save(request.user, request.POST)
                if status[0]:
                    # Has Character, send to that page!
                    url = '/character/{0}/{1}/'.format(
                        status[1]['charid'],
                        status[1]['charname']
                    )
                    return HttpResponseRedirect(url)
                else:
                    return render_to_response(
                        'link_account.html',
                        {'form': form},
                        RequestContext(request)
                    )
            else:
                return render_to_response(
                    'link_account.html', {'form': form}, RequestContext(request)
                )
        else:
            form = LinkAccountForm()
            return render_to_response('link_account.html', {'form': form}, RequestContext(request))
    else:
        return HttpResponseRedirect('/')

def character(request, charid, charname):
    if request.user.is_authenticated():
        if request.POST:
            form = None
            if request.POST['form'] == 'character':
                form = CharacterUpgradeForm(request.POST, charid=charid)
            else:
                form = EnhancedSignetUpgrade(request.POST, charid=charid)
                
            if form.is_valid(request.user):
                saved = form.save(request.user)
                if request.is_ajax():
                    return HttpResponse(saved)
                else:
                    return HttpResponseRedirect('/character/'+charid+"/"+charname+"/")
            else:
                if request.is_ajax():
                    return HttpResponse(request.POST['char_cost'])
                else:
                    return HttpResponseRedirect('/character/'+charid+"/"+charname+"/")
        else:
            form_character = CharacterUpgradeForm(charid=charid)
            form_signet = EnhancedSignetUpgrade(charid=charid)
            return render_to_response('character.html', 
                {'charid':charid, 'charname':charname, 
                'form_character':form_character, 'form_signet':form_signet},
                RequestContext(request)
        )
    else:
        return HttpResponseRedirect('/')

        
def record_feats(request):
    return render_to_response('record_feats.html', {}, RequestContext(request))


def ub3r1337_rank(request):
    return render_to_response('ub3r1337_rank.html', {}, RequestContext(request))


def rewards(request):
    return render_to_response('rewards.html', {}, RequestContext(request))


ffxi/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static "/static/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/static/css/bootstrap-theme.min.css" %}">
    <link rel="stylesheet" href="{% static "/static/css/whhg.css" %}">
    <link rel="stylesheet" href="{% static "/static/css/ffxi.css" %}">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:regular,bold&subset=Latin">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" />
</head>

<body>
    <div class="container">
        <!-- Top Bar -->
        {% include 'base_navbar.html' %}
        <!-- End Top Bar -->
        
         <!-- Main Content-->
        {% block container %}{% endblock %}
        <!-- End Main Content-->
    
        <!-- Footer -->
        <footer class="row text-center black-text">
            <div>
                <hr />
                <div class="copyright">
                    Copyright &#169; 2012-2014 FFXI-Gamify. 
                    All rights reserved. Background image courtesy 
                    of <a href="http://eldi13.deviantart.com/art/Final-Fantasy-XI-logo-255063225">eldi13</a>.
                    {% block courtesy %}{% endblock %}
                </div>
            </div>
        </footer>
        <!-- End Footer -->
    </div>

    <!-- Javascipt -->
    <script src="{% static "/static/js/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "/static/js/bootstrap.min.js" %}"></script>

    {% block js %}
    {% endblock %}
    <!-- End Javascript -->

</body>
</html>

ffxi/templates/base_navbar.html
{% url 'home' as home %}
{% url 'daily_tally' as daily_tally %}
{% url 'characters' as characters %}
{% url 'record_feats' as record_feats %}
{% url 'ub3r1337_rank' as ub3r1337_rank %}
{% load navbar %}
{% load staticfiles %}


{% block navbar %}
    <div class="page-header">
        <ul class="nav nav-pills pull-right">
        {% if user.is_authenticated %}
            <li class="{% active request home %}"><a href="/">Home</a></li>
            {% get_characters user as characters %}
            {% if characters %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                       aria-haspopup="true" aria-expanded="false">
                        Characters
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        {% for id, name in characters.items%}
                            <li><a href="/character/{{ id }}/{{ name }}">{{ name }}</a></li>
                        {% endfor %}
                    </ul>
                 </li>
                 
            {% endif %}
            <li class="{% active request daily_tally %}"><a href="/daily-tally/">Daily Tally</a></li>
            <li class="{% active request record_feats %}"><a href="/record-feats/">Record Feats</a></li>
            <li class="{% active request ub3r1337_rank %}"><a href="/ub3r1337-rank/">Ub3r1337 Rank</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                   aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><a href="/link-account/">Link Account</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Settings</a></li>
                    <li><a href="/accounts/logout/">Sign Out</a></li>
                </ul>
             </li>
        {% else %}
            <li><a href="/accounts/login/">Sign In</a></li>
        {% endif %}
        </ul>
        <div>
            <table>
                <tr>
                    <td>
                        <a href="/">
                            <img src="{% static "/static/img/ffxi-logo.gif" %}" style="width:276px;height:63px;">
                        </a>
                    </td>
                    {% if user.is_authenticated %}
                        {% get_exp_stats user as exp_stats %}
                        <td class="black-text">
                            <table>
                                <tr><td> @{{ user.username }} </td></tr>
                                <tr><td> EXP: <span id="char-exp">{{ exp_stats.exp }}</span></td></tr>
                                <tr><td> EXP Multiplier: <span id="exp-chain">{{ exp_stats.chain }}</span></td></tr>
                            </table>
                        </td>
                    {% endif %}
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

ffxi/templates/character.html
{% extends "base.html" %}
{% load navbar %}
{% load character %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block container %}
<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="row no-margin">
            <!-- First Column -->
            <div class="col-xs-12 col-md-2">
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                      <!-- Default panel contents -->
                      <div class="panel-heading italics">
                        <h3 class="panel-title">{{ charname }}</h3>
                     </div>
                      <!-- Table -->
                      <table class="table italics">
                        {% get_status charid as status %}
                        <tr>
                            <td class="no-border">
                                {% if status.sjob %}
                                    {{ status.mjob }}{{ status.mlvl }}/{{ status.sjob }}{{ status.slvl }}
                                {% else %}
                                    {{ status.mjob }}{{ status.mlvl }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="no-border">{% get_gil charid %} Gil</td>
                        </tr>
                      </table>
                    </div>
                </div>
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                      <!-- Default panel contents -->
                      <div class="panel-heading italics">
                        <h3 class="panel-title">Enhanced Signet</h3>
                      </div>
                      <div class="panel-body italics">
                           Command <strong>@signet</strong>
                      </div>
                      <!-- Table -->
                        <table class="table italics">
                            {% get_enhanced_signet charid %}
                        </table>
                    </div>
                </div>
            </div>
            

            
            <!-- Second Column -->
            <div class="col-xs-12 col-md-4">
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                        <!-- Default panel contents -->
                        <div class="panel-heading italics">
                            <h3 class="panel-title">Title</h3>
                        </div>
                        <div class="panel-body italics">
                            {% get_title charid %}
                        </div>
                    </div>
                </div>
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                        <!-- Default panel contents -->
                        <div class="panel-heading italics">
                            <h3 class="panel-title">Job Levels</h3>
                        </div>
                        <!-- Table -->
                        <table class="table">
                            {% get_jobs charid %}
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- Third Column -->
            <input id="current-exp" name="start_level" type="hidden">
            <div class="col-xs-12 col-md-6">
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                        <!-- Default panel contents -->
                        <div class="panel-heading italics">
                            <h3 class="panel-title">Character Upgrades</h3>
                        </div>
                        <div class="panel-body italics">

                        {% crispy form_character %}

                        </div>
                    </div>
                </div>
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                        <!-- Default panel contents -->
                        <div class="panel-heading italics">
                            <h3 class="panel-title">Enhanced Signet Upgrades</h3>
                        </div>
                        <div class="panel-body italics">
                            {% crispy form_signet %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    <script src="{% static "/static/js/ffxi.js" %}"></script>
    <script>
        {% get_exp_stats user as exp_stats %}
        var exp = {{ exp_stats.exp|cut:"," }};
        var charid = {{charid}};
        var charname = "{{charname}}";
        $(document).ready(function () {       
            disable_input();
            update_exp(exp);
            init_level_form(exp, charid, charname);
            init_signet_form(exp, charid, charname);
        });
    </script>
{% endblock %}

ffxi/templates/character_jobs.html
{% for job, level in jobs.items %}
    {% if level > 0 %}
        {% if forloop.counter|divisibleby:2 %}
            <td class="italics">{{job}}</td>
            <td class="job-{{job|slugify}}">{{level}}</td>
        </tr>
        {% else %}
        <tr>
            <td class="italics">{{job}}</td>
            <td class="job-{{job|slugify}}">{{level}}</td>
        {% endif %}
    {% endif %}
{% endfor %}


ffxi/templates/character_signet.html
{% for name, value in signet.items %}
    <tr>
        <td class="no-border">{{name}}</td>
        <td id="signet-{{name|slugify}}" class="text-right no-border">
        {% if name == 'Regen' %}
            <span class='value'>{{value}}</span> HP/tick
        {% elif name == 'Refresh' %}
            <span class='value'>{{value}}</span> MP/tick
        {% elif name == 'Regain' %}
            <span class='value'>{{value}}</span> TP/tick
        {% else %}
            +<span class='value'>{{value}}</span>%
        {% endif %}
            <span hidden class='level'>{{value}}</span>
         </td>
    </tr>
{% endfor %}

ffxi/templates/daily_tally.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static "/static/css/bootstrap-datepicker3.min.css" %}">
    <style>
        .submit_buttons {
            margin-top: 35px;
        }
        .datepicker {
            padding: 0 !important;
            margin: 0 auto;
        }
        .datepicker-days {
            background-image: linear-gradient(to bottom,#d9edf7 0,#b9def0 100%);
            background-repeat: repeat-x;
            border-color: #9acfea;
            border: 1px solid transparent;
            border-radius: 4px;
            color: #31708f;
            background-color: #d9edf7;
        }
        .asteriskField {
            display: none;
        }
        #update_steps {
            margin-right: 19px;
        }
        label div {
            display: inline;
        }
    </style>
{% endblock %}
{% block container %}
    <div class="row transparent-border">
        <div class="col-xs-12 col-sm-4">
            <div class="row">
                <h4 class="text-center">Choose A Date</h4>
                <div id="datepicker"></div>
                <hr />
                <br />
            </div>
            <div class="row">
                <div class="col-md-3"><img id="earth-cluster" class="crystal" src="/static/img/crystals/earth-cluster.png"></img></div>
                <div class="col-md-3"><img id="water-cluster" class="crystal" src="/static/img/crystals/water-cluster.png"></img></div>
                <div class="col-md-3"><img id="wind-cluster" class="crystal" src="/static/img/crystals/wind-cluster.png"></img></div>
                <div class="col-md-3"><img id="fire-cluster" class="crystal" src="/static/img/crystals/fire-cluster.png"></img></div>
            </div>
            <div class="row">
                <br /> <br />
            </div>
            <div class="row">
                <div class="col-md-3"><img id="ice-cluster" class="crystal" src="/static/img/crystals/ice-cluster.png"></img></div>
                <div class="col-md-3"><img id="lightning-cluster" class="crystal" src="/static/img/crystals/lightning-cluster.png"></img></div>
                <div class="col-md-3"><img id="dark-cluster" class="crystal" src="/static/img/crystals/dark-cluster.png"></img></div>
                <div class="col-md-3"><img id="light-cluster" class="crystal" src="/static/img/crystals/light-cluster.png"></img></div>
            </div>
            <div class="row">
            <br/>
            <div class="progress">
              <div class="progress-bar progress-bar-info exp-chain" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">

              </div>
            </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-8">
            <div class="row">
                <div class="text-center">
                    <h3>Log Your Daily Tally</h3>
                    <p class="indent">
                        Each of the daily tasks is linked to one of the 8 crystals. By completing 
                        a certain number of repetitions you will gain the corresponding crystal. 
                        Collecting all 8 crystals begins or keeps your experience streak! Green 
                        text means you've earned the crystal!
                    </p>
                    <hr/>
                </div>
            </div>
            <div class="row">
                <div>
                {% crispy form %}
                </div>
            </div>   
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static "/static/js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "/static/js/ffxi.js" %}"></script>
    <script>
        $(document).ready(function () {       
            init_datepicker();
            init_stats_form();
            
        });
        $('#id_steps').attr('disabled', true);
    </script>
{% endblock %}

ffxi/templates/daily_tasks.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static "/static/css/bootstrap-datepicker3.min.css" %}">
    <style>
        .submit_buttons {
            margin-top: 35px;
        }
        .datepicker {
            padding: 0 !important;
            margin: 0 auto;
        }
        .datepicker-days {
            background-image: linear-gradient(to bottom,#d9edf7 0,#b9def0 100%);
            background-repeat: repeat-x;
            border-color: #9acfea;
            border: 1px solid transparent;
            border-radius: 4px;
            color: #31708f;
            background-color: #d9edf7;
        }
        .asteriskField {
            display: none;
        }
        #update_steps {
            margin-right: 19px;
        }
        label div {
            display: inline;
        }
    </style>
{% endblock %}
{% block container %}
    <div class="row transparent-border">
        <div class="col-xs-12 col-sm-4">
            <div class="row">
                <h4 class="text-center">Choose A Date</h4>
                <div id="datepicker"></div>
                <hr />
                <br />
            </div>
            <div class="row">
                <div class="col-md-3"><img id="earth-cluster" class="crystal" src="/static/img/crystals/earth-cluster.png"></img></div>
                <div class="col-md-3"><img id="water-cluster" class="crystal" src="/static/img/crystals/water-cluster.png"></img></div>
                <div class="col-md-3"><img id="wind-cluster" class="crystal" src="/static/img/crystals/wind-cluster.png"></img></div>
                <div class="col-md-3"><img id="fire-cluster" class="crystal" src="/static/img/crystals/fire-cluster.png"></img></div>
            </div>
            <div class="row">
                <br /> <br />
            </div>
            <div class="row">
                <div class="col-md-3"><img id="ice-cluster" class="crystal" src="/static/img/crystals/ice-cluster.png"></img></div>
                <div class="col-md-3"><img id="lightning-cluster" class="crystal" src="/static/img/crystals/lightning-cluster.png"></img></div>
                <div class="col-md-3"><img id="dark-cluster" class="crystal" src="/static/img/crystals/dark-cluster.png"></img></div>
                <div class="col-md-3"><img id="light-cluster" class="crystal" src="/static/img/crystals/light-cluster.png"></img></div>
            </div>
            <div class="row">
            <br/>
            <div class="progress">
              <div class="progress-bar progress-bar-info exp-chain" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">

              </div>
            </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-8">
            <div class="row">
                <div class="text-center">
                    <h3>Log Your Daily Tasks</h3>
                    <p class="indent">
                        Each of the daily tasks is linked to one of the 8 crystals. By completing 
                        a certain number of repetitions you will gain the corresponding crystal. 
                        Collecting all 8 crystals begins or keeps your experience streak! Green 
                        text means you've earned the crystal!
                    </p>
                    <hr/>
                </div>
            </div>
            <div class="row">
                <div>
                {% crispy form %}
                </div>
            </div>   
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static "/static/js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "/static/js/ffxi.js" %}"></script>
    <script>
        $(document).ready(function () {       
            init_datepicker();
            init_stats_form();
            
        });
        $('#id_steps').attr('disabled', true);
    </script>
{% endblock %}

ffxi/templates/index.html
{% extends "base.html" %}
{% block container %}
    <div class="row">
        <div>
            <h3>Home</h3>
            <hr />
        </div>
    </div>
{% endblock %}

ffxi/templates/link_account.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}FFXI Gamify - Link Account{% endblock %}

{% block container %}

<div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
        <div class="row no-margin">
            <div class="panel panel-default no-border">
                <!-- Default panel contents -->
                <div class="panel-heading italics">
                    <h3 class="panel-title">
                        Earn 100k Just By Linking Your DSP Account*
                    </h3>
                </div>
                <div class="panel-body italics">
                    <p>
                        By linking your DSP account you can begin to apply daily
                        experience gains to your in-game characters! All you need 
                        to do is provide your DSP info so we can verify you 
                        are the owner of the account.
                    </p>
                    <p>
                        Disclaimer!!!! 100k is only shelled out for the first 
                        three accounts, after that you are on your own!
                    </p>

                    <hr/>
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

ffxi/templates/record_feats.html
{% extends "base.html" %}
{% block container %}
    <div class="row">
        <div>
            <h3>Home</h3>
            <hr />
        </div>
    </div>
{% endblock %}

ffxi/templates/ub3r1337_rank.html
{% extends "base.html" %}
{% load staticfiles %}
{% block container %}
<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="row no-margin">
            <!-- First Column -->
            <div class="col-xs-12 col-md-4">
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                      <div class="panel-heading italics">
                        <h3 class="panel-title">Ub3r1337 Rank</h3>
                     </div>
                    </div>
                </div>
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                      <div class="panel-heading italics">
                        <h3 class="panel-title">Bonus Stats</h3>
                      </div>
                    </div>
                </div>
            </div>
            
            <!-- Second Column -->
            <div class="col-xs-12 col-md-8">
                <div class="row no-margin">
                    <div class="panel panel-default no-border">
                        <!-- Default panel contents -->
                        <div class="panel-heading italics">
                            <h3 class="panel-title">Challenges [Category]</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    <script src="{% static "/static/js/ffxi.js" %}"></script>
{% endblock %}